import type { Metadata } from "next";
import "./globals.css";
import { rubik } from "./fonts";


export const metadata: Metadata = {
  title: "FStyle - Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={rubik.className}>{children}</body>
    </html>
  );
}
